[package]
name = "vif-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
fern = "0.6.2"
clap = "4.5.0"
lazy_static = "1.4.0"
log = "0.4.20"
